apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: te9tjo76l-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/te9tjo76l-dotnet-basic-gitops